### ISSUE TITLE
Error response from daemon: Get https://mydocker-registry/v2/: Not Found

### ISSUE THREAD

**Issue by jessiezhou0424** [dragonflyoss/Dragonfly#1010]
## Question

------------------------------------------------question-----------------------------------------
i use docker pull after deploy dragonfly but get this error:
Error response from daemon: Get https://mydocker-registry/v2/: Not Found

------------------------------------------------enviroment------------------------------------
### what i changed on Node server:
add HTTPS proxy = http://127.0.0.1:65001 and restart dockerd
add http certs dragonfly need.

### all dragonfly agent and supernode are deployed by this yaml:
 ```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: supernode
  namespace: kube-system
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: supernode
    spec:
      nodeSelector:
        dragonfly-type: supernode
      containers:
      - name: supernode
        image: silenceshell/supernode:0.2.0
        imagePullPolicy: Always
        ports:
        - containerPort: 8001
        - containerPort: 8002
        volumeMounts:
        - mountPath: /home/admin/supernode
          name: data
      volumes:
      - name: data
        hostPath:
          path: /var/lib/docker/dragonfly
          type: Directory
---
apiVersion: v1
kind: Service
metadata:
  name: supernode
  namespace: kube-system
  labels:
    svc: supernode
spec:
  ports:
  - port: 8001
    name: port1
    protocol: TCP
    targetPort: 8001
  - port: 8002
    name: port2
    protocol: TCP
    targetPort: 8002
  selector:
    app: supernode
  sessionAffinity: None
---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  labels:
    k8s-app: df-daemon
  name: df-daemon
  namespace: kube-system
spec:
  selector:
    matchLabels:
      k8s-app: df-daemon
  template:
    metadata:
      labels:
        k8s-app: df-daemon
    spec:
      nodeSelector:
        dragonfly-type: agent
      containers:
      - env:
        - name: REGISTRY
          value: https://mydocker-registry
        image: silenceshell/df-daemon:0.2.0
        name: df-daemon
        volumeMounts:
        - mountPath: /etc/dragonfly.conf
          name: config
          readOnly: true
          subPath: dragonfly.conf
        - mountPath: /etc/dragonfly/dfdaemon.yml
          name: config
          readOnly: true
          subPath: dfdaemon.yml
        - mountPath: /root/.small-dragonfly/
          name: data
        - mountPath: /certs
          name: certs
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      restartPolicy: Always
      volumes:
      - configMap:
          defaultMode: 384
          name: df-daemon-config
        name: config
      - hostPath:
          path: /data/dfdaemon
        name: data
      - hostPath:
          path: /certs/path
        name: certs
---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    k8s-app: df-daemon
  name: df-daemon-config
  namespace: kube-system
data:
  dragonfly.conf: |-
    [node]
    address=supernode
  dfdaemon.yml: |-
    proxies:
    - regx: blobs/sha256.*
    - regx: mydocker-registry/
      use_https: true
    hijack_https:
      cert: /certs/server.crt
      key: /certs/server.key
      hosts:
      - regx: mydocker-registry
 ```
### the silenceshell/df-daemon:0.2.0 image do one thing:
 ```
df-daemon --registry ${REGISTRY}
 ```
