### ISSUE TITLE
failed to pull images from harbor through supernode

### ISSUE THREAD

**Issue by orange64** [dragonflyoss/Dragonfly#1042]
## Question

I install dragonfly on kubernetes,it can pull images successfully:
`2019-10-30 10:08:51.618 INFO sign:193-1572430124.416 : pull piece task({"taskID":"1d8174175c4fd7746ddf1213f6507578837d66ed5eb76137ffee460b12443b40","superNode":"supernode:8002","dstCid":"192.168.137.7-106-1572430051.752","range":"83886080-88080383","result":503,"status":701,"pieceSize":4194304,"pieceNum":20}) result:{"code":602,"msg":"taskID: 1d8174175c4fd7746ddf1213f6507578837d66ed5eb76137ffee460b12443b40: {\"Code\":9,\"Msg\":\"peer should wait\"}"} and sleep 1.272s
2019-10-30 10:08:52.914 INFO sign:193-1572430124.416 : remaining piece to be written count:0
2019-10-30 10:08:52.931 INFO sign:193-1572430124.416 : wait client writer finish cost:0.017,main qu size:2,client qu size:0
2019-10-30 10:08:52.931 INFO sign:193-1572430124.416 : move src:/root/.small-dragonfly/data/cb27c747-fdf4-4e6c-8a9b-e19e38246392-193-1572430124.416 to dst:/root/.small-dragonfly/dfdaemon/data/cb27c747-fdf4-4e6c-8a9b-e19e38246392 result:true cost:0.000
2019-10-30 10:08:52.931 INFO sign:193-1572430124.416 : download successfully from dragonfly
2019-10-30 10:08:52.932 INFO sign:193-1572430124.416 : download SUCCESS cost:8.516s length:93587077 reason:0`

Then I fellow the steps (https://github.com/dragonflyoss/Dragonfly/pull/1028) to use dragonfly with harbor,but failed to pull images through supernode.When I am downloading  images in harbor,the log does not have any updates.

##Environment
dragonfly install yaml file:
`apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: supernode
  name: supernode
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: supernode
  template:
    metadata:
      labels:
        app: supernode
    spec:
      affinity:  
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: "node-role.kubernetes.io/master"
                  operator: Exists
      tolerations:
      - key: "node-role.kubernetes.io/master"
        operator: "Exists"
        effect: "NoSchedule"
      containers:
      - name: supernode
	    image: dragonflyoss/supernode:0.4.3
	    imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8001
          hostPort: 8001
          name: register
          protocol: TCP
        - containerPort: 8002
          hostPort: 8002
          name: download
          protocol: TCP
        resources:
		  requests:
		    cpu: "2"
			memory: 4Gi
        volumeMounts:
        - mountPath: /home/admin/supernode/logs/
          name: log
        - mountPath: /home/admin/supernode/repo/
          name: data
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      restartPolicy: Always

      nodeSelector:  
        node-role.kubernetes.io/master: ""
      volumes:
      - name: log
	    hostPath:
          path: /data/supernode/log
          type: DirectoryOrCreate
      - name: data
	    hostPath:
          path: /data/supernode/repo/
          type: DirectoryOrCreate

---

kind: Service
apiVersion: v1
metadata:
  name: supernode
  namespace: kube-system
spec:
  selector:
    app: supernode
  ports:
  - name: register
    protocol: TCP
    port: 8001
    targetPort: 8001
  - name: download
    protocol: TCP
    port: 8002
    targetPort: 8002

---

apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels: 
    k8s-app: dfdaemon
  name: dfdaemon
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: dfdaemon
  template:
    metadata:
      labels:
        app: dfdaemon
    spec:
      containers:
      - name: dfdaemon
	    image: dragonflyoss/dfclient:0.4.3
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 250m
        volumeMounts:
        - mountPath: /etc/dragonfly.conf
          subPath: dragonfly.conf
          name: dragonconf
        - mountPath: /root/.small-dragonfly/
            name: data 
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      restartPolicy: Always
      tolerations: 
      - effect: NoExecute
        operator: Exists
      - effect: NoSchedule
        operator: Exists
      volumes:
      - name: dragonconf
        configMap:
          name: dragonfly-conf
          items:
          - key: dragonfly.conf 
            path: dragonfly.conf
      - name: data
	    hostPath: 
		  path: /data/dfdaemon
		  type: DirectoryOrCreate

---
apiVersion: v1
kind: ConfigMap
data:
  dragonfly.conf: |
    [node]
    address=supernode
metadata:
  name: dragonfly-conf
  namespace: kube-system
`

@Starnop

**Comment by orange64** [comment]
I noticed that in docker info:
`Registry: https://index.docker.io/v1/`
is that the problem?

**Comment by Starnop** [comment]
> I noticed that in docker info:
> `Registry: https://index.docker.io/v1/`
> is that the problem?

Please paste the output of `docker info`. THX

**Comment by orange64** [comment]
@Starnop docker info in client:
`HTTP Proxy: http://127.0.0.1:65001
 HTTPS Proxy: http://127.0.0.1:65001
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  192.168.137.6
  127.0.0.0/8
 Registry Mirrors:
  http://127.0.0.1:65001/
 Live Restore Enabled: false
 Product License: Community Engine
`

**Comment by Starnop** [comment]
I think you have no proxy config for your dfdaemon, so it will only proxy the request to docker hub registry. FYI https://github.com/dragonflyoss/Dragonfly/blob/3c19383d1adf4ea532b574ef1cff91f8c376962b/docs/ecosystem/Harbor-with-Dragonfly.md#prepare-the-configuration-file-1

**Comment by orange64** [comment]
I have modified http proxy according to this doc,you can see this in my docker info:
`HTTP Proxy: http://127.0.0.1:65001`

**Comment by Starnop** [comment]
I mean that you haven't config the dfdaemon. Something like this:

```
# cat /etc/dragonfly/dfdaemon.yml
# config the dfget flags according to your own needs, please refer to https://github.com/dragonflyoss/Dragonfly/blob/master/docs/cli_reference/dfget.md
dfget_flags: ["--node","dfsupernode/1","--verbose","-f","Expires&Signature"]
proxies:
  # proxy all http image layer download requests with dfget
  - regx: blobs/sha256.*
hijack_https:
  # key pair is used to hijack https requests between the caller(E.g. dockerd, containerd) and dfdaemon. You can generate them with make df.crt at the root directory of dragonfly project.
  cert: df.crt
  key: df.key
  hosts:
    - regx: core.harbor.domain:32443
      # If your registry uses a self-signed certificate, please provide the certificate
      # or choose to ignore the certificate error with `insecure: true`.
      certs: ["ca.crt"]
```
