### ISSUE TITLE
[feature request]: redirect url for proxy item

### ISSUE THREAD

**Issue by Starnop** [dragonflyoss/Dragonfly#1046]
## Why you need it?

We use the dfdaemon as a proxy to handle the request for the client like dockerd. However, sometimes we need to redirect the request to the specified host just like `proxy_redirect` of Nginx. So I think we need to add a `host` config item to make it possible. 

## How it could be?

```
proxies:
    # proxy requests and redirect
    - regx: registry-regex
      host: registry-regirect-host
```

## Other related information

FYI https://github.com/dragonflyoss/Dragonfly/pull/410
