### ISSUE TITLE
create proxy: load cert: open df.crt: no such file or directory 

### ISSUE THREAD

**Issue by hmthoo** [dragonflyoss/Dragonfly#1078]
## Question
**Document:**
```
hijack_https:
  # key pair is used to hijack https requests between the caller(E.g. dockerd, containerd) and dfdaemon. You can generate them with make df.crt at the root directory of dragonfly project.
  cert: df.crt
  key: df.key
  hosts:
    - regx: core.harbor.domain:32443
      # If your registry uses a self-signed certificate, please provide the certificate
      # or choose to ignore the certificate error with `insecure: true`.
      certs: ["ca.crt"]
```
**Errors log**
```
Error: create dfdaemon from config: create proxy: load cert: open df.crt: no such file or directory
```
What directory should I put in?
