### ISSUE TITLE
Dragonfly with harbor behind corporate proxy

### ISSUE THREAD

**Issue by guillaumelfv** [dragonflyoss/Dragonfly#1312]
## Question

Hello, i did follow the docs about dragonfly with Harbor [Using dragonfly with harbor](https://github.com/dragonflyoss/Dragonfly/blob/08913645b3f87e77a03aa7f9640f467bc3f40f72/docs/ecosystem/Harbor-with-Dragonfly.md). Everything work correctly when i pull images from my private Harbor registry.

But i am unable to pull images from the public docker registry anymore. I got the following error:

> Error response from daemon: Get https://registry-1.docker.io/v2/: Service Unavailable

and dfdaemon debugging just throw:

> 2020-04-28 15:32:44.103 DEBU sign:9625 : Tunneling https request for registry-1.docker.io:443

This is the dfdaemon configuration on one client node:

```
registry_mirror:
   remote: https://index.docker.io
   insecure: false
   certs: []

proxies:
   # proxy all http image layer download requests with dfget
   - regx: blobs/sha256.*

hijack_https:
   cert: /root/dfclient/df.crt
   key: /root/dfclient/df.key
   hosts:
      - regx: redacted.company.com
        certs: [/root/dfclient/company.com]
```

With that i did modify the docker service accordingly to the doc and this is where the issue is i think. I did modify the _/etc/systemd/system/docker.service.d/https-proxy.conf_ and _/etc/systemd/system/docker.service.d/https-proxy.conf_ to use dfdaemon as proxy:

```
[Service]
Environment="HTTPS_PROXY=http://127.0.0.1:65001"
```

But before that it was set to my corporate proxy. If i reset it to my corporate proxy value then i can pull from my private registry and from the public docker registry, but it does not use dragonfly anymore.

It seems that:

- pulling from Harbor private registry is correctly hijack and pull is working (its internal so does not need corporate proxy)
- pulling from public docker registry get proxy by `regx: blobs/sha256.*` and use dfget but it does not goes to my corporate proxy (or use system proxy) hence the service unavailable

Do I understand it correctly ?

Ultimately Is there a way of configuring dragonfly to:

- pull images from harbor private registry through dfget (no proxy)
- pull images from docker public registry through dfget (using corporate proxy)

If you need other info or if its not clear let me know !
