### ISSUE TITLE
goproxy.d7y.io: How about using Dragonfly to build a GOPROXY?

### ISSUE THREAD

**Issue by lowzj** [dragonflyoss/Dragonfly#1327]
## Why you need it?

Just an idea, why don't we use Dragonfly to build a GOPROXY with P2P ability?

## How it could be?

1. modify the code to make the mirror mode of dfdaemon supporting other URLs:
    ```golang
    func (proxy *Proxy) shouldUseDfgetForMirror(req *http.Request) bool {
        // return proxy.registry != nil && !proxy.registry.Direct && transport.NeedUseGetter(req)
        return proxy.registry != nil && !proxy.registry.Direct && proxy.shouldUseDfget(req)
    }
    ```
1. start dfdaemon with mirror mode:
    ```yaml
    registry_mirror:
        # now we can use the existing goproxy server, such as goproxy.cn/goproxy.io/proxy.golang.org
        remote: https://goproxy.cn
    proxies:
        -regx: zip$
    ```
1. set the env GOPROXY and GO111MODULE to enable goproxy
    ```bash
    export GO111MODULE=on
    export GOPROXY=http://127.0.0.1:65001
    ```
1. then we can build our go project and download go package with Dragonfly

---

Furthermore, we can provide a goproxy server with domain `goproxy.d7y.io` and a global supernode with domain `supernode.d7y.io` if possible. And the config of dfdaemon could be:
```yaml
registry_mirror:
    remote: https://goproxy.d7y.io
proxies:
    -regx: zip$
dfget_flags: ["--node", "supernode.d7y.io"]
```
Every Gopher becomes _**EACH OTHER'S GOPROXY**_.^_^.
