### ISSUE TITLE
SeedPeer的TLS配置相关问题

### ISSUE THREAD

**Issue by chisaato** [dragonflyoss/dragonfly#1886]
![image](https://user-images.githubusercontent.com/17796830/205403924-d5441b04-cbf9-49b8-bfd2-27f6089f68a6.png)
如图,这些地方如果打开了 TLS 则需要填写证书. 那这个证书是可以用自己签发的,还是常规 CA 签发的?
![image](https://user-images.githubusercontent.com/17796830/205404015-8d3bea21-45d2-4389-bd87-60e51d8cf852.png)
而此处可以从 manager 签发证书,那这个证书是否可以用于上面的服务呢? 如果可以,这也许是一个新的 Feature  

还是说文档还没完善到这一步? 暂且没有参考?

**Comment by gaius-qi** [comment]
只要是 CA 就可以了，谁签发的都一样。上一个 issue 功能我已经实现完了，参考 #1887。
具体文档是需要完善一下，有兴趣可以在官网 Reference 帮忙完善一个 Security 的文档。

![image](https://user-images.githubusercontent.com/15955374/208399997-54f8cf26-0773-462c-bc99-1216aafecd76.png

官网项目维护在 https://github.com/dragonflyoss/d7y.io

**Comment by karlhjm** [comment]
> 但是同样的, 请求中打码的部分是 IP 也就意味着他在使用 IP+HTTPS. 这给签发证书带来了问题. 签发一张合法的 IP SSL 证书并不容易.
> 
> ![image](https://user-images.githubusercontent.com/17796830/211222251-67d69005-2025-4dcd-9903-d98440563563.png) 此处我配置的是 Let's Encrypt 签发的域名证书,自然是不包含 IP SAN 的. 所以请求失败了.
> 
> 希望此处可以改进一下,使用 Peer 报告给 Manager 的主机名进行连接. 或者在 autoIssue 之后自动装配上自签名证书.

请问你最后是怎么解决给peer签发server证书的呢，目前2.0.10的我试了下也还是sans校验的问题

**Comment by karlhjm** [comment]
比如peer配置如下，peer之间开启了https下载，但是 peer 在 upload 的 65002 端口的server证书使用的是我自签发的，不是自动生成的
```
download:
  calculateDigest: true
  syncPieceViaHTTPS: true
  downloadGRPC:
    security:
      insecure: false
      caCert: /etc/d7y-root-ca-key/ca.crt
      cert: /etc/d7y-peer-server-cert/server.crt
      key: /etc/d7y-peer-server-cert/server.key
      tlsVerify: true
    unixListen:
      socket: ""
  peerGRPC:
    security:
      insecure: false
      caCert: /etc/d7y-root-ca-key/ca.crt
      cert: /etc/d7y-peer-server-cert/server.crt
      key: /etc/d7y-peer-server-cert/server.key
      tlsVerify: true
    tcpListen:
      port: 65000
  perPeerRateLimit: 512Mi
  prefetch: false
  totalRateLimit: 1024Mi
upload:
  rateLimit: 1024Mi
  security:
    insecure: true
    caCert: /etc/d7y-root-ca-key/ca.crt
    cert: /etc/d7y-peer-server-cert/server.crt
    key: /etc/d7y-peer-server-cert/server.key
    tlsVerify: true
  tcpListen:
    port: 65002
```

由于 uploadListener 调用 prepareTCPListener 这里写死了 true
https://github.com/dragonflyoss/Dragonfly2/blob/55473074450570fb560ee0587c14b52c74561f0c/client/daemon/daemon.go#L619
导致 uploadListener 直接就使用了自签发的 server 证书
https://github.com/dragonflyoss/Dragonfly2/blob/55473074450570fb560ee0587c14b52c74561f0c/client/daemon/daemon.go#L544
https://github.com/dragonflyoss/Dragonfly2/blob/55473074450570fb560ee0587c14b52c74561f0c/client/daemon/daemon.go#L569
而peer 65000 grpc 端口由于写死了 false，并不会使用配置里的自签发server证书，使用的是后续动态生成的 server 证书
https://github.com/dragonflyoss/Dragonfly2/blob/55473074450570fb560ee0587c14b52c74561f0c/client/daemon/daemon.go#L608
