### ISSUE TITLE
仓库注入为http加ip时生成的cert.d文件名字错误

### ISSUE THREAD

**Issue by NatureLR** [dragonflyoss/dragonfly#2527]
类似这种
```yaml
containerRuntime:
  containerd:
    enable: true
    injectConfigPath: true
    registries:
      - 'https://ghcr.io'
      - 'http://192.168.1.1'
 ```

其`/etc/containerd/certs.d/`生成的目录名字为http而不是192.168.1.1

应该是下面的命令未正确的提取http://之后的内容导致

```shell
domain=$(echo $registry | sed -e "s,http.://,," | sed "s,:.*,,")
```

测试

```shell 
registry=http://192.168.1.1
echo $registry | sed -e "s,http.://,," | sed "s,:.*,," 
```
- 修改

```shell
echo $registry | awk -F '//' '{printf$2}'
# 或
echo $registry | sed -e "s,http.*://,," | sed "s,:.*,,"
```
