### ISSUE TITLE
Prometheus does not have the monitoring metric "dragonfly_scheduler_host_traffic".

### ISSUE THREAD

**Issue by zsksy123** [dragonflyoss/dragonfly#3046]
Prometheus does not have the monitoring metric "dragonfly_scheduler_host_traffic".

The configuration of kube-prometheus-stack is as follows
```
prometheus:
  prometheusSpec:
    serviceMonitorSelector:
      matchLabels:
        app: dragonfly
    ruleSelector:
      matchLabels:
        app: dragonfly
```
![image](https://github.com/dragonflyoss/Dragonfly2/assets/58408116/5c7b8537-1c84-4247-84c1-0dab23fe9b5e)
![image](https://github.com/dragonflyoss/Dragonfly2/assets/58408116/cb47c0e1-c9e9-4500-b26f-a5e67758d59c)

![image](https://github.com/dragonflyoss/Dragonfly2/assets/58408116/a33734e8-e594-456a-bd1b-8b44c010db24)

![image](https://github.com/dragonflyoss/Dragonfly2/assets/58408116/c84169b6-d5d5-4547-bd7f-58bd697d94a0)

![image](https://github.com/dragonflyoss/Dragonfly2/assets/58408116/d45c86d0-78ee-44ff-875d-2d70c6d1b47e)

![image](https://github.com/dragonflyoss/Dragonfly2/assets/58408116/7600fe65-36c3-4219-9ddb-5e647b5f3394)
@ gaius-qi
