### ISSUE TITLE
No traces when pulling images from ACK containerd

### ISSUE THREAD

**Issue by sigboom** [dragonflyoss/dragonfly#3052]
### Bug report:
k8s version is 1.26, containerd version is 1.6.20, dragonfly helm package verison is 1.1.29

1. The Dragonfly has been deployed on Alibaba Cloud ACK and two registries have been set up
```
  containerd:
    enable: true
    injectConfigPath: true
    registries:
      - "https://ghcr.io"
      - "https://lthub-registry.cn-beijing.cr.aliyuncs.com"
```
2. All services have started logging normally, referencing dfdaemon.
```
dfdaemon:
  enable: true
  config:
    console: true
    verbose: true
    pprofPort: 18066
    jaeger: ""
jaeger:
  enable: true
```
3. The storage is configured with 20Gi to comply with the minimum quota requirement of Alibaba Cloud's cloud disk.
4. Confirm that all local services have been successfully started.
![image](https://github.com/dragonflyoss/Dragonfly2/assets/34954447/89738784-2383-4858-b5b0-5ac866c15d83)
5. Look at backend services, Confirm All Are Accessible Normally
![image](https://github.com/dragonflyoss/Dragonfly2/assets/34954447/16fcecd8-56a1-4ca8-950a-50d0a48c204c)
![image](https://github.com/dragonflyoss/Dragonfly2/assets/34954447/fe1be753-b322-4cdd-b944-2c31e0d8465b)
6. Based on official use cases for testing, corresponding links https://d7y.io/docs/getting-started/quick-start/kubernetes/#containerd-pull-image-back-to-source-for-the-first-time-through-dragonfly
![image](https://github.com/dragonflyoss/Dragonfly2/assets/34954447/094195ff-e4b7-4bf9-9c2b-cef8fa0d4312)
7. Check that the configuration for containerd on the instance is generated correctly
![image](https://github.com/dragonflyoss/Dragonfly2/assets/34954447/0b727cdc-ad4e-4c00-8c71-9abad4f9d685)
8. The correct request records for the official website use case were not found on Jaeger.
![image](https://github.com/dragonflyoss/Dragonfly2/assets/34954447/db0005e9-2c6e-4baf-bd8e-cd4003f39d98)

### Expected behavior:

![image](https://github.com/dragonflyoss/Dragonfly2/assets/34954447/296052d6-b73b-4370-a241-523f868a5b7e)

### How to reproduce it:

Using Helm to Deploy on ACK Cluster
### Environment:

- Dragonfly version: 2.1.30
- OS: 1.26.3-aliyun.1
- Kernel (e.g. `uname -a`): Linux testompub-pub-172.17.29.36static 5.10.112-11.2.al8.x86_64 #1 SMP Mon Aug 1 20:06:08 CST 2022 x86_64 x86_64 x86_64 GNU/Linux
- Others: 
  - containerd: 1.6.20
  - kubelet: Kubernetes v1.26.3-aliyun.1
