### ISSUE TITLE
import object to seedpeer failed

### ISSUE THREAD

**Issue by joee33** [dragonflyoss/dragonfly#3650]
hello，we depoly a seed peer cluster and enable object storage. config maxReplicas = 3，tlsVerify = true，when client upload file，importObjectToSeedPeer report error log:

```
{"level":"info","ts":"2024-11-11 20:40:12.916","caller":"objectstorage/objectstorage.go:421","msg":"upload object archive/v1/cloud_543327045_2361_79.tar.zip meta: http://xxxxxxxx/archive%2Fv1%2Fcloud_543327045_2361_79.tar.zip?Expires=1731329112&OSSAccessKeyId=xxxxxxx&Signature=SH1rO586BRx0o%2BEY0OZ1WIU11dM%3D &common.UrlMeta{state:impl.MessageState{NoUnkeyedLiterals:pragma.NoUnkeyedLiterals{}, DoNotCompare:pragma.DoNotCompare{}, DoNotCopy:pragma.DoNotCopy{}, atomicMessageInfo:(*impl.MessageInfo)(nil)}, sizeCache:0, unknownFields:[]uint8(nil), Digest:\"md5:67d412d17ecf8df6682abcd40e30180f\", Tag:\"\", Range:\"\", Filter:\"Expires&Signature&ns\", Header:map[string]string(nil), Application:\"\", Priority:0}","taskID":"1447ae5560536f498eae2572576333829b5eafc1f104a435d593c728d8b125c3","peerID":"xxxxxxx-1-5f7f94a5-0328-4448-bdec-6ec494cb57cf"}
{"level":"info","ts":"2024-11-11 20:40:12.916","caller":"objectstorage/objectstorage.go:424","msg":"import object archive/v1/cloud_543327045_2361_79.tar.zip to local storage","taskID":"1447ae5560536f498eae2572576333829b5eafc1f104a435d593c728d8b125c3","peerID":"xxxxxx-1-5f7f94a5-0328-4448-bdec-6ec494cb
57cf"}
{"level":"info","ts":"2024-11-11 20:40:12.918","caller":"objectstorage/objectstorage.go:456","msg":"import object archive/v1/cloud_543327045_2361_79.tar.zip to bucket xxxxx","taskID":"1447ae5560536f498eae2572576333829b5eafc1f104a435d593c728d8b125c3","peerID":"xxxx-1-5f7f94a5-0328-4448-bde
c-6ec494cb57cf"}
{"level":"info","ts":"2024-11-11 20:40:12.918","caller":"objectstorage/objectstorage.go:647","msg":"import object archive/v1/cloud_543327045_2361_79.tar.zip to seed peer xxxxxx:65004","taskID":"1447ae5560536f498eae2572576333829b5eafc1f104a435d593c728d8b125c3","peerID":"xxxx-1-5f7f94a5-0328-4
448-bdec-6ec494cb57cf"}
{"level":"error","ts":"2024-11-11 20:40:12.919","caller":"objectstorage/objectstorage.go:649","msg":"import object archive/v1/cloud_543327045_2361_79.tar.zip to seed peer xxxxxx:65004 failed: bad response status 400 Bad Request","taskID":"1447ae5560536f498eae2572576333829b5eafc1f104a435d593c728d8b125c3","peerID":"xxxx-1-5f7f94a5-0328-4448-bdec-6ec494cb57cf","stacktrace":"d7y.io/dragonfly/v2/client/daemon/objectstorage.(*objectStorage).importObjectToSeedPeers\n\t/go/src/d7y.io/dragonfly/v2/client/daemon/objectstorage/objectstorage.go:649\nd7y.io/dragonfly/v2/client/daemon/objectstorage.(*objectSt
orage).putObject.func1\n\t/go/src/d7y.io/dragonfly/v2/client/daemon/objectstorage/objectstorage.go:450"} 
```

**object storage config:**
```
# Object storage service.
objectStorage:
  # Enable object storage service.
  enable: true
  # Filter is used to generate a unique Task ID by
  # filtering unnecessary query params in the URL,
  # it is separated by & character.
  # When filter: "Expires&Signature&ns", for example:
  #  http://localhost/xyz?Expires=111&Signature=222&ns=docker.io and http://localhost/xyz?Expires=333&Signature=999&ns=docker.io
  # is same task.
  filter: 'Expires&Signature&ns'
  # maxReplicas is the maximum number of replicas of an object cache in seed peers.
  maxReplicas: 3
  # Object storage service security option.
  security:
    insecure: false
    tlsVerify: true
    cacert: |-
      xxxxxxx
    cert: |-
      xxxxxxx
    key: |-
      xxxxxxx
  tcpListen:
    # # Listen address.
    # listen: 0.0.0.0
    # Listen port.
    port: 65004
```

https://github.com/dragonflyoss/Dragonfly2/blob/8f6f20b604bb540c39db5fb7020926e6db2dd9c8/client/daemon/objectstorage/objectstorage.go#L661

i wonder how to config a client cert for peed to import file to another seed peer
