### ISSUE TITLE
Why isn't the Dragonfly proxy being used when pulling images from a private registry?

### ISSUE THREAD

**Issue by neilchen12** [dragonflyoss/dragonfly#3905]
After deploying Dragonfly, when executing `crictl pull ${privateRegistryHost}/${image}` on the node, the image can be pulled successfully but does not route through the proxy (no logs related to `​task_id` were detected in the client pod). However, when using `crictl pull 127.0.0.1:4001/${image}` to directly access the proxy, the image is successfully pulled and cached by Dragonfly.

Why isn't the Dragonfly proxy being used when pulling images from a private registry?

Helm Chart Version: dragonfly-1.3.15

CRI-O VERSION：1.32.2

 <details><summary>Helm values</summary>

```yaml
manager:
  replicas: 1
  image:
    tag: v2.2.1

scheduler:
  replicas: 1
  image:
    tag: v2.2.1

seedClient:
  replicas: 1
  image:
    tag: v0.2.19
  extraVolumes:
    - name: storage
      hostPath:
        path: /var/lib/dragonfly-seed-client/storage
  persistence:
    enable: false
  config:
    proxy:
      server:
        port: 4001
      rules:
        - regex: "blobs/sha256.*"
      registryMirror:
        addr: https://${privateRegistryHost}
      disableBackToSource: false
      prefetch: true

client:
  image:
    tag: v0.2.19
  extraVolumes:
    - name: storage
      hostPath:
        path: /var/lib/dragonfly-client/storage
  extraVolumeMounts:
    - name: storage
      mountPath: /var/lib/dragonfly/
  dfinit:
    enable: true
    image:
      tag: v0.2.19
    config:
      verbose: true
      log:
        level: info
      proxy:
        addr: http://127.0.0.1:4001
      containerRuntime:
        containerd: null
        crio:
          configPath: /etc/crio/crio.conf.d/01-crio.conf
          unqualifiedSearchRegistries: ["docker.io"]
          registries:
            - prefix: ${privateRegistryHost}
              location: ${privateRegistryHost}
  config:
    proxy:
      registryMirror:
        addr: https://${privateRegistryHost}

mysql:
  enable: true
  architecture: standalone

redis:
  enable: true
  architecture: standalone
```

</details>

<details><summary>CRI-O configurations</summary>

![Image](https://github.com/user-attachments/assets/69e5bce0-f24a-4dbb-b844-bfb4e7e9c57e)

</details>

</details>

<details><summary>CRI-O logs (private registry)</summary>

![Image](https://github.com/user-attachments/assets/238a10ec-c067-48c9-a97f-5980448b1e95)

</details>

<details><summary>CRI-O logs (dragonfly proxy)</summary>

![Image](https://github.com/user-attachments/assets/bf74d152-7dfe-45c6-bd08-90eadf4c40ce)

</details>
