### ISSUE TITLE
preheat large size image some blob return  rpc error: code = Internal desc = error decoding response body

### ISSUE THREAD

**Issue by luozhijunroy18** [dragonflyoss/dragonfly#3928]
### Bug report:
this is my helm install values.yaml
```
# Dragonfly Helm Chart Values.
global:
  imageRegistry: "registry-prod.xxx.com/library"
  storageClass: ""

manager:
  resources:
    limits:
      cpu: "1"
      memory: "1Gi"
  initContainer:
    resources:
      limits:
        cpu: "1"
        memory: "1Gi"
  ingress:
    enable: true
    className: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
    hosts:
      - dragonfly.k8s02.xxx.net
    auth:
      jwt:
        # -- Realm name to display to the user, default value is Dragonfly.
        realm: "Dragonfly"
        # -- Key is secret key used for signing, default value is
        # encoded base64 of dragonfly.
        # Please change the key in production.
        key: "xxxxx"
        # -- Timeout is duration that a jwt token is valid,
        # default duration is two days.
        timeout: 48h
        # -- MaxRefresh field allows clients to refresh their token
        # until MaxRefresh has passed, default duration is two days.
        maxRefresh: 48h
    cache:
      redis:
        # -- Redis cache TTL duration.
        ttl: 5m
      local:
        # -- Size of LFU cache.
        size: 30000
        # -- Local cache TTL duration.
        ttl: 3m

scheduler:
  resources:
    limits:
      cpu: "1"
      memory: "1Gi"
  initContainer:
    resources:
      limits:
        cpu: "1"
        memory: "1Gi"

seedClient:
  resources:
    limits:
      cpu: "1"
      memory: "1Gi"
  initContainer:
    resources:
      limits:
        cpu: "1"
        memory: "1Gi"
  persistence:
    size: 50Gi

client:
  resources:
    limits:
      cpu: "1"
      memory: "2Gi"
  initContainer:
    resources:
      limits:
        cpu: "1"
        memory: "1Gi"
  dfinit:
    # -- Enable dfinit to override configuration of container runtime.
    enable: true
    config:
      # -- verbose prints log.
      verbose: true
      log:
        # -- Specify the logging level [trace, debug, info, warn, error]
        level: info
      proxy:
        # -- addr is the proxy server address of dfdaemon.
        addr: http://127.0.0.1:4001
      containerRuntime:
        containerd:
          # -- configPath is the path of containerd configuration file.
          configPath: /etc/containerd/config.toml
          # -- registries is the list of containerd registries. hostNamespace is the location where container images and artifacts are sourced,
          # refer to https://github.com/containerd/containerd/blob/main/docs/hosts.md#registry-host-namespace. The registry host namespace
          # portion is [registry_host_name|IP address][:port], such as docker.io, ghcr.io, gcr.io, etc. serverAddr specifies the default server
          # for this registry host namespace, refer to https://github.com/containerd/containerd/blob/main/docs/hosts.md#server-field.
          # capabilities is the list of capabilities in containerd configuration, refer to
          # https://github.com/containerd/containerd/blob/main/docs/hosts.md#capabilities-field.
          # skip_verify is the flag to skip verifying the server's certificate, refer to
          # https://github.com/containerd/containerd/blob/main/docs/hosts.md#bypass-tls-verification-example.
          # ca (Certificate Authority Certification) can be set to a path or an array of paths each pointing
          # to a ca file for use in authenticating with the registry namespace, refer to
          # https://github.com/containerd/containerd/blob/main/docs/hosts.md#ca-field.
          registries:
            - hostNamespace: xxx-repo.tencentcloudcr.com
              serverAddr: https://xxx-repo.tencentcloudcr.com
              capabilities: ["pull", "resolve"]
              skipVerify: true
              # ca: []
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                  - k8s02-node04
                  - k8s02-node05
```
when i use curl to preheat
```
curl -skL --location --request POST "${d7y_manger_url}/oapi/v1/jobs" \
        -H "Accept: application/json" \
        --header "Authorization: Bearer ${d7y_manger_jwt}" \
        --header 'Content-Type: application/json' \
        --data-raw '{"type": "preheat","args": {"type": "image", "url": "https://xxx-repo.tencentcloudcr.com/v2/xxx/whispered-all-in-one/manifests/develop-20250402103611-8c50de6c", "username": "dragonfly-preheat", "password": "xxx", "scope": "single_seed_peer", "scope": "single_seed_peer", "scheduler_cluster_ids":[1]}}'
```
return response
```
{
    "id": 18,
    "created_at": "0001-01-01T00:00:00Z",
    "updated_at": "0001-01-01T00:00:00Z",
    "is_del": 0,
    "task_id": "group_36e8dffd-34f2-4d99-9940-cd468bf62e73",
    "bio": "",
    "type": "preheat",
    "state": "PENDING",
    "args": {
        "concurrent_count": 50,
        "filtered_query_params": "xxx",
        "headers": null,
        "password": "xxx",
        "piece_length": null,
        "platform": "",
        "scope": "single_seed_peer",
        "tag": "",
        "timeout": 1800000000000,
        "type": "image",
        "url": "https://xxx-repo.tencentcloudcr.com/v2/xxx/whispered-all-in-one/manifests/develop-20250402103611-8c50de6c",
        "username": "dragonfly-preheat"
    },
    "result": null,
    "user_id": 0,
    "user": {
        "id": 0,
        "created_at": "0001-01-01T00:00:00Z",
        "updated_at": "0001-01-01T00:00:00Z",
        "is_del": 0,
        "email": "",
        "name": "",
        "avatar": "",
        "phone": "",
        "state": "",
        "location": "",
        "bio": "",
        "configs": null
    },
    "seed_peer_clusters": null,
    "scheduler_clusters": [
        {
            "id": 1,
            "created_at": "2025-04-01T03:51:54Z",
            "updated_at": "2025-04-01T03:51:54Z",
            "is_del": 0,
            "name": "cluster-1",
            "bio": "",
            "config": {
                "candidate_parent_limit": 4,
                "filter_parent_limit": 15,
                "job_rate_limit": 10
            },
            "client_config": {
                "load_limit": 200
            },
            "scopes": {},
            "is_default": true,
            "seed_peer_clusters": null,
            "schedulers": null,
            "peers": null,
            "jobs": null
        }
    ]
}
```
after several minutes，exec this curl return FAILURE
```
curl --header "Authorization: Bearer xxxx" --request GET 'http://dragonfly.k8s02.xxx.net/oapi/v1/jobs/18'

{
    "id": 17,
    "created_at": "2025-04-02T08:48:17Z",
    "updated_at": "2025-04-02T08:50:08Z",
    "is_del": 0,
    "task_id": "group_468509f1-0adf-4feb-bddd-8574550c4f91",
    "bio": "",
    "type": "preheat",
    "state": "FAILURE",
    "args": {
        "concurrent_count": 50,
        "filtered_query_params": "xxx",
        "headers": null,
        "password": "xxx",
        "piece_length": null,
        "platform": "",
        "scope": "single_seed_peer",
        "tag": "",
        "timeout": 1800000000000,
        "type": "image",
        "url": "https://xxx-repo.tencentcloudcr.com/v2/xxx/whispered-all-in-one/manifests/develop-20250402103611-8c50de6c",
        "username": "dragonfly-preheat"
    },
    "result": {
        "created_at": "2025-04-02T08:48:17.492018399Z",
        "group_uuid": "group_468509f1-0adf-4feb-bddd-8574550c4f91",
        "job_states": [
            {
                "created_at": "2025-04-02T08:48:17.489024883Z",
                "error": "",
                "results": [
                    {
                        "failure_tasks": null,
                        "scheduler_cluster_id": 1,
                        "success_tasks": [
                            {
                                "hostname": "dragonfly-seed-client-2",
                                "ip": "100.57.182.163",
                                "url": "https://xxx-repo.tencentcloudcr.com/v2/xxx/whispered-all-in-one/blobs/sha256:dfd33d631c957b6e7e8e2089c5c05b8984303aff8b72734d74950fcead669886"
                            }
                        ]
                    }
                ],
                "state": "SUCCESS",
                "task_name": "preheat",
                "task_uuid": "task_6576277e-7500-40de-be68-d36b63c70039",
                "ttl": 0
            },
            {
                "created_at": "2025-04-02T08:48:17.490460481Z",
                "error": "",
                "results": [
                    {
                        "failure_tasks": null,
                        "scheduler_cluster_id": 1,
                        "success_tasks": [
                            {
                                "hostname": "dragonfly-seed-client-2",
                                "ip": "100.57.182.163",
                                "url": "https://xxx-repo.tencentcloudcr.com/v2/xxx/whispered-all-in-one/blobs/sha256:3dd181f9be599de628e1bc6d868d517125e07f968824bcf7b7ed8d28ad1026b1"
                            }
                        ]
                    }
                ],
                "state": "SUCCESS",
                "task_name": "preheat",
                "task_uuid": "task_13acf087-a496-40cd-8c45-915420618561",
                "ttl": 0
            },
            {
                "created_at": "2025-04-02T08:48:17.492018399Z",
                "error": "rpc error: code = Internal desc = error decoding response body",
                "results": null,
                "state": "FAILURE",
                "task_name": "preheat",
                "task_uuid": "task_c2dcb095-359f-4934-bf65-a469225a8106",
                "ttl": 0
            },
            {
                "created_at": "2025-04-02T08:48:17.49362717Z",
                "error": "",
                "results": [
                    {
                        "failure_tasks": null,
                        "scheduler_cluster_id": 1,
                        "success_tasks": [
                            {
                                "hostname": "dragonfly-seed-client-0",
                                "ip": "100.56.207.169",
                                "url": "https://xxx-repo.tencentcloudcr.com/v2/xxx/whispered-all-in-one/blobs/sha256:fcdf82cbe4eb323290897e9d752b7b4f95a52dd4cf42affce239a93b1fda268d"
                            }
                        ]
                    }
                ],
                "state": "SUCCESS",
                "task_name": "preheat",
                "task_uuid": "task_40179eb8-9ba6-4997-a6b3-b285edff652c",
                "ttl": 0
            },
            {
                "created_at": "2025-04-02T08:48:17.495182728Z",
                "error": "",
                "results": [
                    {
                        "failure_tasks": null,
                        "scheduler_cluster_id": 1,
                        "success_tasks": [
                            {
                                "hostname": "dragonfly-seed-client-0",
                                "ip": "100.56.207.169",
                                "url": "https://xxx-repo.tencentcloudcr.com/v2/xxx/whispered-all-in-one/blobs/sha256:1bcc0786d8d5cc196d864618ed34d937a23b183fccd6b6a1610fe3b97a2fbdff"
                            }
                        ]
                    }
                ],
                "state": "SUCCESS",
                "task_name": "preheat",
                "task_uuid": "task_14ff6771-1bd9-4863-9bf8-f338efcf9fd7",
                "ttl": 0
            },
            {
                "created_at": "2025-04-02T08:48:17.496755133Z",
                "error": "",
                "results": [
                    {
                        "failure_tasks": null,
                        "scheduler_cluster_id": 1,
                        "success_tasks": [
                            {
                                "hostname": "dragonfly-seed-client-2",
                                "ip": "100.57.182.163",
                                "url": "https://xxx-repo.tencentcloudcr.com/v2/xxx/whispered-all-in-one/blobs/sha256:c06a84945f550496044b8478391d9399846ab31f5b14b2d381254a1aa08f8e3e"
                            }
                        ]
                    }
                ],
                "state": "SUCCESS",
                "task_name": "preheat",
                "task_uuid": "task_2872af8f-68e6-473b-8632-d321fb08661b",
                "ttl": 0
            },
            {
                "created_at": "2025-04-02T08:48:17.498802654Z",
                "error": "",
                "results": [
                    {
                        "failure_tasks": null,
                        "scheduler_cluster_id": 1,
                        "success_tasks": [
                            {
                                "hostname": "dragonfly-seed-client-2",
                                "ip": "100.57.182.163",
                                "url": "https://xxx-repo.tencentcloudcr.com/v2/xxx/whispered-all-in-one/blobs/sha256:d259b1ea0499dd54ab89951dfbb07a7dffdf81c3c954505ce02562cd403ae62c"
                            }
                        ]
                    }
                ],
                "state": "SUCCESS",
                "task_name": "preheat",
                "task_uuid": "task_2ea8fe08-58b9-4ccc-9bea-3be1c84d4af7",
                "ttl": 0
            },
            {
                "created_at": "2025-04-02T08:48:17.500439071Z",
                "error": "",
                "results": [
                    {
                        "failure_tasks": null,
                        "scheduler_cluster_id": 1,
                        "success_tasks": [
                            {
                                "hostname": "dragonfly-seed-client-1",
                                "ip": "100.54.146.255",
                                "url": "https://xxx-repo.tencentcloudcr.com/v2/xxx/whispered-all-in-one/blobs/sha256:0684057b86d39d28ce7049af9349207213cab78a5bba21ddc7a8dbaae13b20fa"
                            }
                        ]
                    }
                ],
                "state": "SUCCESS",
                "task_name": "preheat",
                "task_uuid": "task_4c6a6ea2-42cc-4d64-887a-5cca374a3037",
                "ttl": 0
            },
            {
                "created_at": "2025-04-02T08:48:17.501834756Z",
                "error": "rpc error: code = Internal desc = error decoding response body",
                "results": null,
                "state": "FAILURE",
                "task_name": "preheat",
                "task_uuid": "task_45777b94-be20-474e-9e6e-6a8b0687d5cb",
                "ttl": 0
            },
            {
                "created_at": "2025-04-02T08:48:17.502889726Z",
                "error": "rpc error: code = Internal desc = error decoding response body",
                "results": null,
                "state": "FAILURE",
                "task_name": "preheat",
                "task_uuid": "task_b0d83b22-1d85-4e5a-8927-8df28ee52d20",
                "ttl": 0
            },
            {
                "created_at": "2025-04-02T08:48:17.506375873Z",
                "error": "rpc error: code = Internal desc = error decoding response body",
                "results": null,
                "state": "FAILURE",
                "task_name": "preheat",
                "task_uuid": "task_58025384-1043-44b3-93ed-d072d27d0215",
                "ttl": 0
            },
            {
                "created_at": "2025-04-02T08:48:17.507484234Z",
                "error": "",
                "results": [
                    {
                        "failure_tasks": null,
                        "scheduler_cluster_id": 1,
                        "success_tasks": [
                            {
                                "hostname": "dragonfly-seed-client-2",
                                "ip": "100.57.182.163",
                                "url": "https://xxx-repo.tencentcloudcr.com/v2/xxx/whispered-all-in-one/blobs/sha256:b65a07a9cc7ae417b21031bdcf3598f6908be1276b6324ffc8ff1a09cbb93254"
                            }
                        ]
                    }
                ],
                "state": "SUCCESS",
                "task_name": "preheat",
                "task_uuid": "task_b45da554-5d7b-42a8-8af6-9aad3855fa0f",
                "ttl": 0
            },
            {
                "created_at": "2025-04-02T08:48:17.508960991Z",
                "error": "",
                "results": [
                    {
                        "failure_tasks": null,
                        "scheduler_cluster_id": 1,
                        "success_tasks": [
                            {
                                "hostname": "dragonfly-seed-client-1",
                                "ip": "100.54.146.255",
                                "url": "https://xxx-repo.tencentcloudcr.com/v2/xxx/whispered-all-in-one/blobs/sha256:be96192526e125cbf7eb2733b035ea42d88d0b89aad12b6ac512e9db19583042"
                            }
                        ]
                    }
                ],
                "state": "SUCCESS",
                "task_name": "preheat",
                "task_uuid": "task_3143a9fb-5f92-42d6-8f9f-638c25480f35",
                "ttl": 0
            },
            {
                "created_at": "2025-04-02T08:48:17.510635981Z",
                "error": "",
                "results": [
                    {
                        "failure_tasks": null,
                        "scheduler_cluster_id": 1,
                        "success_tasks": [
                            {
                                "hostname": "dragonfly-seed-client-2",
                                "ip": "100.57.182.163",
                                "url": "https://xxx-repo.tencentcloudcr.com/v2/xxx/whispered-all-in-one/blobs/sha256:b486cf5e205e9fd7181939ac724c29c7bd3caa61e9fe253807c08a248b02097d"
                            }
                        ]
                    }
                ],
                "state": "SUCCESS",
                "task_name": "preheat",
                "task_uuid": "task_f1433369-3698-48c4-98d2-5ec8f6e268a5",
                "ttl": 0
            },
            {
                "created_at": "2025-04-02T08:48:17.512423283Z",
                "error": "",
                "results": [
                    {
                        "failure_tasks": null,
                        "scheduler_cluster_id": 1,
                        "success_tasks": [
                            {
                                "hostname": "dragonfly-seed-client-0",
                                "ip": "100.56.207.169",
                                "url": "https://xxx-repo.tencentcloudcr.com/v2/xxx/whispered-all-in-one/blobs/sha256:a8a082f4e2ff3c8662ee83afbb65ba3e54ddf24278d635e97de678fdd1c07b4d"
                            }
                        ]
                    }
                ],
                "state": "SUCCESS",
                "task_name": "preheat",
                "task_uuid": "task_3b232d47-e99e-4d4c-886e-cccac192438d",
                "ttl": 0
            },
            {
                "created_at": "2025-04-02T08:48:17.513837792Z",
                "error": "",
                "results": [
                    {
                        "failure_tasks": null,
                        "scheduler_cluster_id": 1,
                        "success_tasks": [
                            {
                                "hostname": "dragonfly-seed-client-1",
                                "ip": "100.54.146.255",
                                "url": "https://xxx-repo.tencentcloudcr.com/v2/xxx/whispered-all-in-one/blobs/sha256:4cfb025299272e83e32f9f57423971a9709dc84a13f437869d341d93c392b037"
                            }
                        ]
                    }
                ],
                "state": "SUCCESS",
                "task_name": "preheat",
                "task_uuid": "task_86f488b9-e777-41f2-bc6f-95c874f7b3e6",
                "ttl": 0
            }
        ],
        "state": "FAILURE",
        "updated_at": "2025-04-02T08:50:08.064515137Z"
    },
    "user_id": 0,
    "user": {
        "id": 0,
        "created_at": "0001-01-01T00:00:00Z",
        "updated_at": "0001-01-01T00:00:00Z",
        "is_del": 0,
        "email": "",
        "name": "",
        "avatar": "",
        "phone": "",
        "state": "",
        "location": "",
        "bio": "",
        "configs": null
    },
    "seed_peer_clusters": [],
    "scheduler_clusters": [
        {
            "id": 1,
            "created_at": "2025-04-01T03:51:54Z",
            "updated_at": "2025-04-01T03:51:54Z",
            "is_del": 0,
            "name": "cluster-1",
            "bio": "",
            "config": {
                "candidate_parent_limit": 4,
                "filter_parent_limit": 15,
                "job_rate_limit": 10
            },
            "client_config": {
                "load_limit": 200
            },
            "scopes": {},
            "is_default": true,
            "seed_peer_clusters": null,
            "schedulers": null,
            "peers": null,
            "jobs": null
        }
    ]
}
```
for task_c2dcb095-359f-4934-bf65-a469225a8106 in pod dragonfly-manager logs

![Image](https://github.com/user-attachments/assets/f2ac3c62-0365-4261-8bed-f5734de0587b)

<img width="1427" alt="Image" src="https://github.com/user-attachments/assets/983a1556-45fd-4a98-b14f-73f87b2ff784" />

<img width="1380" alt="Image" src="https://github.com/user-attachments/assets/f54d583c-b2b0-4f09-9c07-c6b5b0a71180" />

```
k logs dragonfly-seed-client-2 | grep 6d733e6219d966050b2455fb6cac42788c07045994fb8bce47da65dbc145020e
Defaulted container "seed-client" out of: seed-client, wait-for-manager (init)
  2025-04-02T08:23:32.872259835+00:00  INFO  download task started: Download { url: "https://xxx-repo.tencentcloudcr.com/v2/xxx/whispered-all-in-one/blobs/sha256:6d733e6219d966050b2455fb6cac42788c07045994fb8bce47da65dbc145020e", digest: None, range: None, r#type: Standard, tag: Some(""), application: Some(""), priority: Level0, filtered_query_params: ["X-Amz-Algorithm", "X-Amz-Credential", "X-Amz-Date", "X-Amz-Expires", "X-Amz-SignedHeaders", "X-Amz-Signature", "X-Amz-Security-Token", "X-Amz-User-Agent", "X-Goog-Algorithm", "X-Goog-Credential", "X-Goog-Date", "X-Goog-Expires", "X-Goog-SignedHeaders", "X-Goog-Signature", "OSSAccessKeyId", "Expires", "Signature", "SecurityToken", "AccessKeyId", "Signature", "Expires", "X-Obs-Date", "X-Obs-Security-Token", "q-sign-algorithm", "q-ak", "q-sign-time", "q-key-time", "q-header-list", "q-url-param-list", "q-signature", "x-cos-security-token", "ns"], request_header: {"Accept": "application/vnd.docker.image.rootfs.diff.tar.gzip", "Authorization": "Bearer xxx"}, piece_length: None, output_path: None, timeout: None, disable_back_to_source: false, need_back_to_source: false, certificate_chain: [], prefetch: false, object_storage: None, hdfs: None, is_prefetch: false, need_piece_content: false, load_to_cache: false, force_hard_link: false }
  2025-04-02T08:48:17.863876214+00:00  INFO  download task started: Download { url: "https://xxx-repo.tencentcloudcr.com/v2/xxx/whispered-all-in-one/blobs/sha256:6d733e6219d966050b2455fb6cac42788c07045994fb8bce47da65dbc145020e", digest: None, range: None, r#type: Standard, tag: Some(""), application: Some(""), priority: Level0, filtered_query_params: ["X-Amz-Algorithm", "X-Amz-Credential", "X-Amz-Date", "X-Amz-Expires", "X-Amz-SignedHeaders", "X-Amz-Signature", "X-Amz-Security-Token", "X-Amz-User-Agent", "X-Goog-Algorithm", "X-Goog-Credential", "X-Goog-Date", "X-Goog-Expires", "X-Goog-SignedHeaders", "X-Goog-Signature", "OSSAccessKeyId", "Expires", "Signature", "SecurityToken", "AccessKeyId", "Signature", "Expires", "X-Obs-Date", "X-Obs-Security-Token", "q-sign-algorithm", "q-ak", "q-sign-time", "q-key-time", "q-header-list", "q-url-param-list", "q-signature", "x-cos-security-token", "ns"], request_header: {"Accept": "application/vnd.docker.image.rootfs.diff.tar.gzip", "Authorization": "Bearer xxx"}, piece_length: None, output_path: None, timeout: None, disable_back_to_source: false, need_back_to_source: false, certificate_chain: [], prefetch: false, object_storage: None, hdfs: None, is_prefetch: false, need_piece_content: false, load_to_cache: false, force_hard_link: false }
  2025-04-02T09:32:17.265701005+00:00  INFO  download task started: Download { url: "https://xxx-repo.tencentcloudcr.com/v2/xxx/whispered-all-in-one/blobs/sha256:6d733e6219d966050b2455fb6cac42788c07045994fb8bce47da65dbc145020e", digest: None, range: None, r#type: Standard, tag: Some(""), application: Some(""), priority: Level0, filtered_query_params: ["X-Amz-Algorithm", "X-Amz-Credential", "X-Amz-Date", "X-Amz-Expires", "X-Amz-SignedHeaders", "X-Amz-Signature", "X-Amz-Security-Token", "X-Amz-User-Agent", "X-Goog-Algorithm", "X-Goog-Credential", "X-Goog-Date", "X-Goog-Expires", "X-Goog-SignedHeaders", "X-Goog-Signature", "OSSAccessKeyId", "Expires", "Signature", "SecurityToken", "AccessKeyId", "Signature", "Expires", "X-Obs-Date", "X-Obs-Security-Token", "q-sign-algorithm", "q-ak", "q-sign-time", "q-key-time", "q-header-list", "q-url-param-list", "q-signature", "x-cos-security-token", "ns"], request_header: {"Authorization": "Bearer xxx", "Accept": "application/vnd.docker.image.rootfs.diff.tar.gzip"}, piece_length: None, output_path: None, timeout: None, disable_back_to_source: false, need_back_to_source: false, certificate_chain: [], prefetch: false, object_storage: None, hdfs: None, is_prefetch: false, need_piece_content: false, load_to_cache: false, force_hard_link: false }
  2025-04-02T09:43:34.660835171+00:00  INFO  download task started: Download { url: "https://xxx-repo.tencentcloudcr.com/v2/xxx/whispered-all-in-one/blobs/sha256:6d733e6219d966050b2455fb6cac42788c07045994fb8bce47da65dbc145020e", digest: None, range: None, r#type: Standard, tag: Some(""), application: Some(""), priority: Level0, filtered_query_params: ["X-Amz-Algorithm", "X-Amz-Credential", "X-Amz-Date", "X-Amz-Expires", "X-Amz-SignedHeaders", "X-Amz-Signature", "X-Amz-Security-Token", "X-Amz-User-Agent", "X-Goog-Algorithm", "X-Goog-Credential", "X-Goog-Date", "X-Goog-Expires", "X-Goog-SignedHeaders", "X-Goog-Signature", "OSSAccessKeyId", "Expires", "Signature", "SecurityToken", "AccessKeyId", "Signature", "Expires", "X-Obs-Date", "X-Obs-Security-Token", "q-sign-algorithm", "q-ak", "q-sign-time", "q-key-time", "q-header-list", "q-url-param-list", "q-signature", "x-cos-security-token", "ns"], request_header: {"Authorization": "Bearer xxx", "Accept": "application/vnd.docker.image.rootfs.diff.tar.gzip"}, piece_length: None, output_path: None, timeout: None, disable_back_to_source: false, need_back_to_source: false, certificate_chain: [], prefetch: false, object_storage: None, hdfs: None, is_prefetch: false, need_piece_content: false, load_to_cache: false, force_hard_link: false }
```

<img width="1413" alt="Image" src="https://github.com/user-attachments/assets/d9a0060c-6f88-4298-aa02-607589a2d9f9" />

### Environment:

- Dragonfly version:  helm 1.3.17
- OS:  containerd://1.5.5
k8s Server Version: v1.22.8
- Kernel (e.g. `uname -a`):Linux k8s02-node07 3.10.0-1160.59.1.el7.x86_64 #1 SMP Wed Feb 23 16:47:03 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
- Others:
BTW：
my containerd://1.5.5 not file /etc/containerd/config.toml, i exec containerd config default > /etc/containerd/config.toml  , dragonfly-client Running

![Image](https://github.com/user-attachments/assets/a826c285-9c08-4a21-bbfb-0f0f14d58b4f)
