### ISSUE TITLE
Memory leak in dragonfly client

### ISSUE THREAD

**Issue by neilchen12** [dragonflyoss/dragonfly#3964]
### Bug report:

The memory usage of dragonfly-client continuously increases over time without being released, eventually reaching the pod's memory limit and causing an OOM crash. It seems that the memory increases every five minutes, which appears to be related to the configuration of  `client.config.scheduler.announceInterval` .

<details><summary> memory usage</summary>

![Image](https://github.com/user-attachments/assets/7dd50f3a-53c6-407d-90fa-625b094afb34)

</details>

### Expected behavior:

The memory usage of dragonfly-client should remain stable when no image downloads are occurring.

### How to reproduce it:

Deploy Dragonfly 2.2.1 using Helm Chat, and the helm values are as follows:

<details><summary>helm  values</summary>

```yaml
fullnameOverride: infras-dragonfly

global:
  imageRegistry: {{ REGISTRY_HOST }}

manager:
  enable: true
  name: manager
  replicas: 1
  image:
    repository: service-dragonfly-manager
    tag: v2.2.1
    pullPolicy: IfNotPresent
  resources:
    requests:
      cpu: 0.2
      memory: 200Mi
    limits:
      cpu: 2
      memory: 400Mi
  priorityClassName: system-cluster-critical
  podLabels:
    project: infras
    service: infras-dragonfly-manager
  config:
    databaseType: postgres

scheduler:
  enable: true
  name: scheduler
  replicas: 1
  image:
    repository: service-dragonfly-scheduler
    tag: v2.2.1
    pullPolicy: IfNotPresent
  resources:
    requests:
      cpu: 0.2
      memory: 200Mi
    limits:
      cpu: 2
      memory: 400Mi
  priorityClassName: system-cluster-critical
  config:
    scheduler:
      retryBackToSourceLimit: 30
      retryLimit: 30
      retryInterval: 1000ms
seedClient:
  enable: true
  name: seed-client
  replicas: 1
  image:
    repository: service-dragonfly-client
    tag: v0.2.19
    pullPolicy: IfNotPresent
  resources:
    requests:
      cpu: 0.5
      memory: 4000Mi
    limits:
      cpu: 2
      memory: 4000Mi
  extraVolumes:
    - name: logs
      hostPath:
        path: /app/infras-dragonfly-seed-client/logs
    - name: storage
      hostPath:
        path: /app/infras-dragonfly-seed-client/storage    
  extraVolumeMounts:
    - name: logs
      mountPath: /var/log/dragonfly/dfdaemon/
  persistence:
    enable: false
  config:
    verbose: false
    log:
      level: error
    download:
      pieceTimeout: 30m
    storage:
      writeBufferSize: 10485760
      readBufferSize: 10485760
    proxy:
      server:
        port: 65001
      registryMirror:
        addr: https://{{ REGISTRY_HOST }}

client:
  enable: true
  name: client
  image:
    repository: service-dragonfly-client
    tag: v0.2.19
    pullPolicy: IfNotPresent
  resources:
    requests:
      cpu: 0.01
      memory: 500Mi
    limits:
      cpu: 2
      memory: 500Mi
  tolerations:
  - operator: Exists
  extraVolumes:
    - name: storage
      hostPath:
        path: /app/infras-dragonfly-client/storage
    - name: logs
      hostPath:
        path: /app/infras-dragonfly-client/logs
  extraVolumeMounts:
    - name: storage
      mountPath: /var/lib/dragonfly/
    - name: logs
      mountPath: /var/log/dragonfly/dfdaemon/
  dfinit:
    enable: false
  config:
    verbose: false
    log:
      level: error
    download:
      pieceTimeout: 30m
    storage:
      writeBufferSize: 10485760
      readBufferSize: 10485760
    proxy:
      server:
        port: 65001
      registryMirror:
        addr: https://{{ REGISTRY_HOST }}

mysql:
  enable: false

postgres:
  enable: false

externalPostgres:
  username: {{ POSTGRES_USER }}
  password: {{ POSTGRES_PASSWORD }}
  host: {{ POSTGRES_HOST }}
  port: 5432
  dbname: dragonfly
  sslMode: disable
  migrate: true

redis:
  enable: false

externalRedis:
  addrs:
    - {{ REDIS_HOST }}
  masterName: ""
  username: ""
  password: {{ REDIS_PASSWORD }}
  db: 9
  brokerDB: 9
  backendDB: 9
```

</details>

### Environment:

- Dragonfly version: 2.2.1
- Dragonfly client version：0.2.19
- OS: Ubuntu 24.04.2
- Kernel : 6.8.0-1021-azure
- K8s: v1.32.2
- CRI-O: v1.32.2

I've upgraded the dragonfly client to version 0.2.23, but the problem still persists.

**Comment by gaius-qi** [comment]
@neilchen12 Please deploy according to the minimum resource configuration, refer to https://d7y.io/docs/next/operations/best-practices/deployment-best-practices/#cluster. Client uses memory more than 500Mi.

```yaml
client:
  resources:
    limits:
      cpu: 2
      memory: 4Gi
```
