### ISSUE TITLE
How to configure a proxy server

### ISSUE THREAD

**Issue by zsksy123** [dragonflyoss/dragonfly#3981]
My configuration is as follows
```
dfdaemon:
    config:
        resourceClients:
            https:
                proxy: "http://10.96.2.59:7890"
            http:
                proxy: "http://10.96.2.59:7890"
```
However, it has not taken effect.
Is there any problem with the configuration? I hope you can correct it.
