### ISSUE TITLE
[feature request] Extend dfdaemon's proxy mode

### ISSUE THREAD

**Issue by inoc603** [dragonflyoss/Dragonfly#478]
## Why you need it?

It would be great if we can set `HTTP_PROXY=http://dfdaemon` and speed up HTTP requests for any third party tools that respects the `HTTP_PROXY` environment variable out of the box.

A good example would be speeding up package managers like yum, apt, npm, maven and others that can use HTTP download.

The current registry proxy can be implemented with this too.

HTTPS requests are more tricky, the best we can do at the moment might be just proxying it over HTTP, without looking at the content. This will handle cases where the client needs both HTTPS and HTTP requests like #449 

## How it could be?

We need a way to describe the proxy rules like `registries` in dfdaemon's config, for example:

```yaml
proxy:
  # a regexp that will be checked against the url, probably without the scheme since
  # we can only actually handle http requests
- match: regexp
  # change the proxy target and scheme, as the current registry proxy does.
  # maybe we can also provide a way rewrite host like the nginx rewrite syntax
  change_host: example.host
  change_scheme: https
  # like the urlfilter parameter, but works for individual rules, merged with global settings
  query_filters:
    - Signature
    - Expires
    - OSSAccessKeyId
  # whether to use p2p to download, like the rule cli parameter
  p2p: true
```

We can first read the rules from config file, and maybe provide apis to dynamically change the rules later.
