### ISSUE TITLE
[feature] Use the same port for reverse proxy and transparent proxy

### ISSUE THREAD

**Issue by inoc603** [dragonflyoss/Dragonfly#534]
## Why you need it?

Currently we use 2 different ports for the reverse proxy which mainly used as registry mirror, and the transparent proxy which is meant to be used for `HTTP_PROXY`.  These two proxies' function have some overlap, and it may be confusing for the user. Technically, we can use the same port for both and make configuration simpler. `/debug` and other handlers can also be served with this port.

## How it could be?

We can easily tell a proxy request from a normal request from the request URL. It's very easy to implement, but some changes need to be made about the current configuration.

I propose using reverse proxy only for the official registry mirror. As recommended in https://github.com/dragonflyoss/website/pull/35 , multiple registries are supported via `HTTP_PROXY`. So we can change the `registries` configuration back to configure the reverse mirror only, and all `HTTP_PROXY` related configuration goes to `proxies`.

```yaml
registry_mirror:
  remote: https://index.docker.io
  # optional certificates. maybe we don't need it since private registries are meant to
  # be supported with http_proxy ?
  certs: []
  # maybe we should add a regexp to filter requests?
  # or we can use blobs/sha256 by default

proxies:
  # ...

hijack_https:
  # ...
```
