### ISSUE TITLE
[feature request] Support non-ipv4 format node address for dfclient

### ISSUE THREAD

**Issue by yeya24** [dragonflyoss/Dragonfly#679]
### Ⅰ. Issue Description
In my k8s environment, dfclient specifies node address with k8s service name. However, dfget cannot register this supernode IP to supernode because currently it only accepts ipv4 format address. We should support non-ipv4 format node address as well.

``` bash
tail -f dfclient.log
2019-07-17 10:57:28.147 INFO sign:87-1563361048.138 : do register to supernode.default.svc.cluster.local:8002, res:null error:500:{"message":"{\"Code\":501,\"Msg\":\"validation failure list:\nsuperNodeIp in body must be of type ipv4: \"supernode.default.svc.cluster.local\": {\"Code\":2,\"Msg\":\"invalid value\"}\"}"}

2019-07-17 10:57:28.147 ERRO sign:87-1563361048.138 : register to node:supernode.default.svc.cluster.local:8002 error:500:{"message":"{\"Code\":501,\"Msg\":\"validation failure list:\nsuperNodeIp in body must be of type ipv4: \"supernode.default.svc.cluster.local\": {\"Code\":2,\"Msg\":\"invalid value\"}\"}"}
```

### Ⅱ. Describe what happened
Cannot work normally when specifies non-ipv4 format node address.

### Ⅲ. Describe what you expected to happen
Peer registered successfully.

### Ⅳ. How to reproduce it (as minimally and precisely as possible)
You can reproduce this issue by following steps.
1. Here are two yaml files. Use `kubectl apply -f dfclient.yaml supernode.yaml` to apply them.

dfclient yaml:
``` yaml
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: dfclient
  labels:     
    app: dfclient
spec:
  selector:
    matchLabels:
      app: dfclient
  template:
    metadata:
      labels:         
        app: dfclient
    spec:
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      containers:
        - name: dfclient
          image: "dragonflyoss/dfclient:0.4.1"
          args:
            - --node=supernode.default.svc.cluster.local:8002
          ports:
            - name: proxy
              containerPort: 65001
              protocol: TCP
```
supernode yaml:
``` yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: supernode
spec:
  replicas: 2
  selector:
    matchLabels:
      app: supernode
  template:
    metadata:
      labels:
        app: supernode
    spec:
      containers:
      - name: supernode
        image: dragonflyoss/supernode:0.4.1
        ports:
        - containerPort: 8002
          name: http
          protocol: TCP 
        - containerPort: 8001
          name: nginx
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: supernode
  name: supernode
spec:
  type: ClusterIP
  ports:
    - port: 8002
      name: http
      targetPort: http
      protocol: TCP
    - port: 8001
      name: nginx
      targetPort: nginx
      protocol: TCP 
  selector:
    app: supernode
```
2. docker pull some images
3. checkout logs of dfclient

### Ⅵ. Environment:

- dragonfly version:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:
