### ISSUE TITLE
multi-mirrors can be supported by binding different hosts for 127.0.0.1 

### ISSUE THREAD

**Issue by zcc35357949** [dragonflyoss/Dragonfly#945]
## Why you need it?
Although using proxy can make no sense to image users, this approach need to restart dockerd for enabling `HTTP_PROXY` and `HTTPS_PROXY`. The costs of restarting dockerd in all machines is too high. Using dragonfly as mirror may be more suitable, I can pull images through dragonfly by the format like `docker pull 127.0.0.1: 65001 / ref` without restarting dockerd.

As noted in #525 , currently mirroring multiple registries is not supported.

## How it could be?
Because dfdaemon can't know the current request is for which registry mirror.
If we bind `127.0.0.1` to a custom host, dfdaemon can match mirror registries by the custom host.

For example:
dfdaemon config:
```
registry_mirrors:
- remote: https://aa.registry.co
  certs: ["/etc/docker/certs.d/aa.registry.co/ca.crt"]
  insecure: false
- remote: https://bb.registry.co
  certs: ["/etc/docker/certs.d/bb.registry.co/ca.crt"]
  insecure: false
```

Then bind hosts in clients:
```
127.0.0.1     localhost   dragonfly.aa.registry.co    dragonfly.bb.registry.co
```

Dfdaemon can get the request url's host, If host is `dragonfly.aa.registry.co`, set `aa.registry.co` as the reserve proxy target.And If host is `dragonfly.bb.registry.co`, use  `bb.registry.co` mirror config.
